spring:
  # 数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 5233711314Dlx@

  # 文件上传的配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 阿里云oss
#aliyun:
#  oss:
#    endpoint: http://oss-cn-hangzhou.aliyuns.com
#    accessKeyId:
#    accessKeySecret:
#    bucketName: web-tlias

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
